// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"go-app/domain"

	"github.com/pgvector/pgvector-go"
	mock "github.com/stretchr/testify/mock"
)

// NewEmbeddingHTTPRepository creates a new instance of EmbeddingHTTPRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEmbeddingHTTPRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *EmbeddingHTTPRepository {
	mock := &EmbeddingHTTPRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// EmbeddingHTTPRepository is an autogenerated mock type for the EmbeddingHTTPRepository type
type EmbeddingHTTPRepository struct {
	mock.Mock
}

type EmbeddingHTTPRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *EmbeddingHTTPRepository) EXPECT() *EmbeddingHTTPRepository_Expecter {
	return &EmbeddingHTTPRepository_Expecter{mock: &_m.Mock}
}

// GetGeneralEmbedding provides a mock function for the type EmbeddingHTTPRepository
func (_mock *EmbeddingHTTPRepository) GetGeneralEmbedding(ctx context.Context, sentence string, vType domain.VectorType) (*pgvector.Vector, error) {
	ret := _mock.Called(ctx, sentence, vType)

	if len(ret) == 0 {
		panic("no return value specified for GetGeneralEmbedding")
	}

	var r0 *pgvector.Vector
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, domain.VectorType) (*pgvector.Vector, error)); ok {
		return returnFunc(ctx, sentence, vType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, domain.VectorType) *pgvector.Vector); ok {
		r0 = returnFunc(ctx, sentence, vType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pgvector.Vector)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, domain.VectorType) error); ok {
		r1 = returnFunc(ctx, sentence, vType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// EmbeddingHTTPRepository_GetGeneralEmbedding_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGeneralEmbedding'
type EmbeddingHTTPRepository_GetGeneralEmbedding_Call struct {
	*mock.Call
}

// GetGeneralEmbedding is a helper method to define mock.On call
//   - ctx context.Context
//   - sentence string
//   - vType domain.VectorType
func (_e *EmbeddingHTTPRepository_Expecter) GetGeneralEmbedding(ctx interface{}, sentence interface{}, vType interface{}) *EmbeddingHTTPRepository_GetGeneralEmbedding_Call {
	return &EmbeddingHTTPRepository_GetGeneralEmbedding_Call{Call: _e.mock.On("GetGeneralEmbedding", ctx, sentence, vType)}
}

func (_c *EmbeddingHTTPRepository_GetGeneralEmbedding_Call) Run(run func(ctx context.Context, sentence string, vType domain.VectorType)) *EmbeddingHTTPRepository_GetGeneralEmbedding_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 domain.VectorType
		if args[2] != nil {
			arg2 = args[2].(domain.VectorType)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *EmbeddingHTTPRepository_GetGeneralEmbedding_Call) Return(vector *pgvector.Vector, err error) *EmbeddingHTTPRepository_GetGeneralEmbedding_Call {
	_c.Call.Return(vector, err)
	return _c
}

func (_c *EmbeddingHTTPRepository_GetGeneralEmbedding_Call) RunAndReturn(run func(ctx context.Context, sentence string, vType domain.VectorType) (*pgvector.Vector, error)) *EmbeddingHTTPRepository_GetGeneralEmbedding_Call {
	_c.Call.Return(run)
	return _c
}
