// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"go-app/domain"

	"github.com/google/uuid"
	"github.com/pgvector/pgvector-go"
	mock "github.com/stretchr/testify/mock"
)

// NewJournalRepository creates a new instance of JournalRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewJournalRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *JournalRepository {
	mock := &JournalRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// JournalRepository is an autogenerated mock type for the JournalRepository type
type JournalRepository struct {
	mock.Mock
}

type JournalRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *JournalRepository) EXPECT() *JournalRepository_Expecter {
	return &JournalRepository_Expecter{mock: &_m.Mock}
}

// GetJournal provides a mock function for the type JournalRepository
func (_mock *JournalRepository) GetJournal(ctx context.Context, id uuid.UUID) (*domain.Journal, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetJournal")
	}

	var r0 *domain.Journal
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Journal, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Journal); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Journal)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// JournalRepository_GetJournal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetJournal'
type JournalRepository_GetJournal_Call struct {
	*mock.Call
}

// GetJournal is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *JournalRepository_Expecter) GetJournal(ctx interface{}, id interface{}) *JournalRepository_GetJournal_Call {
	return &JournalRepository_GetJournal_Call{Call: _e.mock.On("GetJournal", ctx, id)}
}

func (_c *JournalRepository_GetJournal_Call) Run(run func(ctx context.Context, id uuid.UUID)) *JournalRepository_GetJournal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *JournalRepository_GetJournal_Call) Return(journal *domain.Journal, err error) *JournalRepository_GetJournal_Call {
	_c.Call.Return(journal, err)
	return _c
}

func (_c *JournalRepository_GetJournal_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*domain.Journal, error)) *JournalRepository_GetJournal_Call {
	_c.Call.Return(run)
	return _c
}

// GetJournalList provides a mock function for the type JournalRepository
func (_mock *JournalRepository) GetJournalList(ctx context.Context, filter *domain.JournalFilter, embedding *pgvector.Vector) ([]domain.JournalResponse, error) {
	ret := _mock.Called(ctx, filter, embedding)

	if len(ret) == 0 {
		panic("no return value specified for GetJournalList")
	}

	var r0 []domain.JournalResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.JournalFilter, *pgvector.Vector) ([]domain.JournalResponse, error)); ok {
		return returnFunc(ctx, filter, embedding)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.JournalFilter, *pgvector.Vector) []domain.JournalResponse); ok {
		r0 = returnFunc(ctx, filter, embedding)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.JournalResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.JournalFilter, *pgvector.Vector) error); ok {
		r1 = returnFunc(ctx, filter, embedding)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// JournalRepository_GetJournalList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetJournalList'
type JournalRepository_GetJournalList_Call struct {
	*mock.Call
}

// GetJournalList is a helper method to define mock.On call
//   - ctx context.Context
//   - filter *domain.JournalFilter
//   - embedding *pgvector.Vector
func (_e *JournalRepository_Expecter) GetJournalList(ctx interface{}, filter interface{}, embedding interface{}) *JournalRepository_GetJournalList_Call {
	return &JournalRepository_GetJournalList_Call{Call: _e.mock.On("GetJournalList", ctx, filter, embedding)}
}

func (_c *JournalRepository_GetJournalList_Call) Run(run func(ctx context.Context, filter *domain.JournalFilter, embedding *pgvector.Vector)) *JournalRepository_GetJournalList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.JournalFilter
		if args[1] != nil {
			arg1 = args[1].(*domain.JournalFilter)
		}
		var arg2 *pgvector.Vector
		if args[2] != nil {
			arg2 = args[2].(*pgvector.Vector)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *JournalRepository_GetJournalList_Call) Return(journalResponses []domain.JournalResponse, err error) *JournalRepository_GetJournalList_Call {
	_c.Call.Return(journalResponses, err)
	return _c
}

func (_c *JournalRepository_GetJournalList_Call) RunAndReturn(run func(ctx context.Context, filter *domain.JournalFilter, embedding *pgvector.Vector) ([]domain.JournalResponse, error)) *JournalRepository_GetJournalList_Call {
	_c.Call.Return(run)
	return _c
}
